"""change embedding dimension to 1024

Revision ID: 113390df7da0
Revises: 0cc6e3fbcd74
Create Date: 2026-08-26 00:41:13.658129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector


# revision identifiers, used by Alembic.
revision: str = '113390df7da0'
down_revision: Union[str, Sequence[str], None] = '0cc6e3fbcd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    # ### end Alembic commands ###
